### ISSUE TITLE
Invalid define LL_AHB2_GRP1_PERIPH_CCM when using a STM32G473xx controller

### ISSUE THREAD

**Issue by Hanuali** [STMicroelectronics/stm32g4xx_hal_driver#10]
We are using an STM32G473VCT6 and the STM32 low level library (not the HAL) version 1.5.2.

The define LL_AHB2_GRP1_PERIPH_CCM in file `stm32g4xx_ll_bus.h` is invalid. If one uses it, one will get a compiler error.

The current define is the following:

`#define LL_AHB2_GRP1_PERIPH_CCM            RCC_AHB2SMENR_CCMSMEN`

But the value `RCC_AHB2SMENR_CCMSMEN` is nowhere set. The most obvious fix for this controller would be:

`#define LL_AHB2_GRP1_PERIPH_CCM            RCC_AHB2SMENR_CCMSRAMSMEN`

as `RCC_AHB2SMENR_CCMSRAMSMEN` is defined in file `stm32g473xx.h`.

The used toolchain is irrelevant to this failure, but we are using Visual Studio Code as IDE with (custom) CMake which uses gnu-tools-for-stm32 with gcc v11.3.

One can reproduce the compiler error if using the following line somewhere in the code:
`LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_CCM);`

**Comment by TOUNSTM** [comment]
ST Internal Reference: 175713
