### ISSUE TITLE
When do stm32 hal can be provided as a cmake component

### ISSUE THREAD

**Issue by AlanCui4080** [STMicroelectronics/stm32g4xx_hal_driver#19]
As what i said, stm32 hal library still provided as old-style zipped package, while some new microcontrollers provided its hal as CMake component to easier construct, all user need is simply include your directory not copying files. CMakeLists.txt generated by CubeMX is stupid to copy every file into working directionary, obviously a reference to global library is more friendly to our disk.
If your source code policy allowed me to get it a CMake support, i'd pleasure to do that.

**Comment by ALABSTM** [comment]
Hi @AlanCui4080,

Thank you for your question and even more for your proposal to help. However, there is currently no plan for such move. Maybe in the mid- or long-term.

Please allow me to close this issue. Thank you for your comprehension.

With regards,
