### ISSUE TITLE
please add a LICENSE file

### ISSUE THREAD

**Issue by mohrr** [STMicroelectronics/stm32g4xx_hal_driver#7]
Please add a LICENSE or LICENSE.md file as described in https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by ASELSTM** [comment]
Hi @mohrr,

Thank you for this report. The [LICENSE.md](https://github.com/STMicroelectronics/stm32g4xx_hal_driver/blob/master/LICENSE.md) file has been restored. 
Please allow me thus to clos this thread. 

With regards,
