### ISSUE TITLE
Lack of FLASH_OB_BootConfig Functionality in STM32G4 HAL Library

### ISSUE THREAD

**Issue by Xuezheng-Sha** [STMicroelectronics/stm32g4xx_hal_driver#9]
Board: STM32G474RET6 or STM32G474RCT6
IDE/Compiler: [Keil µVision 5.36]

Issue Description
The STM32G4 series, specifically the STM32G474RET6 and STM32G474RCT6 chips, are designed to support firmware updates via serial communication by utilizing a dual BANK configuration. In this context, a mechanism to identify the current bank, write to the alternate bank, and subsequently switch between banks is crucial for seamless firmware updates.

For similar chip designs, such as the STM32F4 series, the HAL library provides the FLASH_OB_BootConfig function to facilitate this process. However, it appears that the STM32G4 HAL library lacks this essential functionality.

**Comment by TOUNSTM** [comment]
Hello @Xuezheng-Sha,

Thank you for your contribution.  The **FLASH_OB_UserConfig()** API can be used to configure the Dual Bank Boot option byte for the `STM32G4` series. Given that **FLASH_OB_UserConfig()** API is already available and can handle multiple option bytes, including the Dual Bank Boot configuration, you can use it directly without needing to implement a separate API. For a more detailed explanation, you can see this [FLASH DualBoot](https://github.com/STMicroelectronics/STM32CubeG4/tree/master/Projects/NUCLEO-G474RE/Examples/FLASH/FLASH_DualBoot)  example.

Please allow me to close this issue and thank you again for your report.
Best regards,
